param([Parameter(Mandatory=$true)][string]$VamRoot)
$ErrorActionPreference = 'Stop'
$compiler = Join-Path $env:WINDIR 'Microsoft.NET/Framework64/v4.0.30319/csc.exe'
$temp = Join-Path ([IO.Path]::GetTempPath()) ('VamMonoProbe-' + [guid]::NewGuid())
New-Item -ItemType Directory -Path $temp | Out-Null
try {
    $hostExe = Join-Path $temp 'MonoHost.exe'
    $probeExe = Join-Path $temp 'RuntimeProbe.exe'
    & $compiler /nologo /target:exe /platform:x64 "/out:$hostExe" (Join-Path $PSScriptRoot 'tests/MonoHost.cs')
    if ($LASTEXITCODE -ne 0) { throw 'Host compilation failed' }
    $refs = @('mscorlib.dll','System.dll','System.Core.dll') | ForEach-Object { '/reference:' + (Join-Path $VamRoot "VaM_Data/Managed/$_") }
    & $compiler /nologo /noconfig /nostdlib+ /target:exe "/out:$probeExe" @refs (Join-Path $PSScriptRoot 'tests/RuntimeProbe.cs')
    if ($LASTEXITCODE -ne 0) { throw 'Probe compilation failed' }
    & $hostExe $VamRoot $probeExe (Join-Path $PSScriptRoot 'tests/fixtures/SceneBrowser-1.0.0.dll')
    if ($LASTEXITCODE -ne 1) { throw 'Expected old 1.0.0 to reproduce runtime failure' }
    Write-Output 'PASS: original runtime failure reproduced'
    & $hostExe $VamRoot $probeExe (Join-Path $PSScriptRoot '../../src-tauri/resources/mods/VamLibrary.SceneBrowser.dll')
    if ($LASTEXITCODE -ne 0) { throw 'Fixed plugin failed in game Mono' }
} finally {
    # Only files generated by this test in its unique directory are removed.
    foreach ($name in @('MonoHost.exe','RuntimeProbe.exe')) {
        $file = Join-Path $temp $name
        if (Test-Path -LiteralPath $file) { Remove-Item -LiteralPath $file }
    }
    Remove-Item -LiteralPath $temp
}
